// Stella's Day - kids' to-do list for the Inland ESP32 2.8" display board
// (ESP32-2432S028). Portrait, 240 x 320. Requires TFT_eSPI with the
// board-specific User_Setup.h. Icons are generated by design/make_icons.py.

#include <SPI.h>
#include <TFT_eSPI.h>
#include <XPT2046_Touchscreen.h>
#include "icons.h"
#include "touch_config.h"

TFT_eSPI tft = TFT_eSPI();
TFT_eSprite row = TFT_eSprite(&tft);   // off-screen buffer for one task row
SPIClass touchSpi(VSPI);
XPT2046_Touchscreen ts(XPT_CS, XPT_IRQ);

// ---------- Palette (sampled from design/main_screen_mockup.png) ----------
constexpr uint16_t rgb(uint8_t r, uint8_t g, uint8_t b) {
  return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3);
}
const uint16_t C_BG        = rgb(0xFE, 0xF9, 0xF4);  // cream background
const uint16_t C_HEADER    = rgb(0xFD, 0xE0, 0xF4);  // pink header
const uint16_t C_TITLE     = rgb(0x1A, 0x00, 0x47);  // deep purple text
const uint16_t C_MINT      = rgb(0xDC, 0xF7, 0xE5);  // done card
const uint16_t C_LAVENDER  = rgb(0xEE, 0xEE, 0xF8);  // to-do card
const uint16_t C_YELLOW    = rgb(0xFE, 0xEA, 0xAB);  // special / one-off card
const uint16_t C_GREEN     = rgb(0x32, 0x97, 0x5D);  // checked box
const uint16_t C_BOX_LINE  = rgb(0xB9, 0x8C, 0xF6);  // unchecked box border
const uint16_t C_PINK      = rgb(0xFD, 0x69, 0xA5);  // accent (nav buttons)
const uint16_t C_DOT       = rgb(0xEE, 0xDB, 0xFD);  // inactive page dot
const uint16_t C_DONE_TEXT = rgb(0x5A, 0x64, 0x70);  // greyed text on done rows
const uint16_t C_WHITE     = TFT_WHITE;

// ---------- Layout (pixels) ----------
const int SCREEN_W   = 240;
const int SCREEN_H   = 320;
const int HEADER_H   = 64;
const int ROW_X      = 8;
const int ROW_W      = 224;
const int ROW_H      = 40;
const int ROW_GAP    = 5;
const int ROW_Y0     = 70;
const int ROWS_PER_PAGE = 5;
const int BOX_SIZE   = 28;
const int NAV_Y      = 305;

// ---------- Data ----------
struct Task {
  const char*     name;
  const char*     time;     // "" for none
  const uint16_t* icon;
  bool            special;  // one-off event (yellow card)
  bool            done;
};

Task tasks[] = {
  { "Brush teeth",     "",        icon_toothbrush, false, true  },
  { "Get dressed",     "",        icon_shirt,      false, false },
  { "Eat breakfast",   "",        icon_cereal,     false, true  },
  { "Soccer practice", "4:00 PM", icon_soccer,     true,  false },
  { "Read a book",     "",        icon_books,      false, false },
};
const int NUM_TASKS = sizeof(tasks) / sizeof(tasks[0]);

const char* dateLabel = "Mon, Sep 15";   // will come from NTP later

// ---------- Drawing ----------
// Sprites can't pushImage() with a transparent key, so draw icons pixel by pixel
void drawIcon(TFT_eSprite& s, int x, int y, const uint16_t* icon) {
  for (int j = 0; j < ICON_SIZE; j++) {
    for (int i = 0; i < ICON_SIZE; i++) {
      uint16_t c = icon[j * ICON_SIZE + i];
      if (c != ICON_KEY) s.drawPixel(x + i, y + j, c);
    }
  }
}

void drawCheckbox(TFT_eSprite& s, int x, int y, bool done) {
  if (done) {
    s.fillRoundRect(x, y, BOX_SIZE, BOX_SIZE, 7, C_GREEN);
    // Check mark: short stroke down-right, long stroke up-right
    s.drawWideLine(x + 7,  y + 14, x + 12, y + 19, 3.5, C_WHITE, C_GREEN);
    s.drawWideLine(x + 12, y + 19, x + 21, y + 9,  3.5, C_WHITE, C_GREEN);
  } else {
    s.fillRoundRect(x, y, BOX_SIZE, BOX_SIZE, 7, C_WHITE);
    s.drawRoundRect(x, y, BOX_SIZE, BOX_SIZE, 7, C_BOX_LINE);
    s.drawRoundRect(x + 1, y + 1, BOX_SIZE - 2, BOX_SIZE - 2, 6, C_BOX_LINE);
  }
}

void drawRow(int index) {
  if (index < 0 || index >= NUM_TASKS) return;
  const Task& t = tasks[index];
  int y = ROW_Y0 + index * (ROW_H + ROW_GAP);

  uint16_t card = t.done ? C_MINT : (t.special ? C_YELLOW : C_LAVENDER);
  uint16_t text = t.done ? C_DONE_TEXT : C_TITLE;

  row.fillSprite(C_BG);
  row.fillRoundRect(0, 0, ROW_W, ROW_H, 10, card);
  drawIcon(row, 6, (ROW_H - ICON_SIZE) / 2, t.icon);

  row.setTextColor(text, card);
  row.setTextDatum(ML_DATUM);
  row.setFreeFont(&FreeSansBold9pt7b);
  if (t.time[0]) {
    row.drawString(t.name, 46, 14);
    row.setFreeFont(&FreeSans9pt7b);
    row.drawString(t.time, 46, 30);
  } else {
    row.drawString(t.name, 46, ROW_H / 2);
  }

  drawCheckbox(row, ROW_W - BOX_SIZE - 8, (ROW_H - BOX_SIZE) / 2, t.done);
  row.pushSprite(ROW_X, y);
}

void drawHeader() {
  // Rounded bottom corners only: start the rect above the screen edge
  tft.fillRoundRect(0, -16, SCREEN_W, HEADER_H + 16, 16, C_HEADER);

  tft.pushImage(12, 12, ICON_SIZE, ICON_SIZE, icon_heart, ICON_KEY);
  tft.pushImage(196, 26, ICON_SIZE, ICON_SIZE, icon_flower, ICON_KEY);

  tft.setTextColor(C_TITLE, C_HEADER);
  tft.setTextDatum(TC_DATUM);
  tft.setFreeFont(&FreeSansBold12pt7b);
  tft.drawString("Stella's Day", SCREEN_W / 2, 10);
  tft.setFreeFont(&FreeSans9pt7b);
  tft.drawString(dateLabel, SCREEN_W / 2, 38);
}

void drawArrowButton(int cx, int cy, bool pointRight) {
  tft.fillCircle(cx, cy, 11, C_PINK);
  int d = pointRight ? 1 : -1;
  tft.drawWideLine(cx - 5 * d, cy, cx + 5 * d, cy, 2.5, C_WHITE, C_PINK);
  tft.drawWideLine(cx + 5 * d, cy, cx + 1 * d, cy - 4, 2.5, C_WHITE, C_PINK);
  tft.drawWideLine(cx + 5 * d, cy, cx + 1 * d, cy + 4, 2.5, C_WHITE, C_PINK);
}

void drawNav(int page, int pages) {
  tft.fillRect(0, NAV_Y - 14, SCREEN_W, 28, C_BG);
  drawArrowButton(24, NAV_Y, false);
  drawArrowButton(SCREEN_W - 24, NAV_Y, true);
  int x0 = SCREEN_W / 2 - (pages - 1) * 7;
  for (int i = 0; i < pages; i++) {
    tft.fillCircle(x0 + i * 14, NAV_Y, 4, i == page ? C_PINK : C_DOT);
  }
}

void drawScreen() {
  tft.fillScreen(C_BG);
  drawHeader();
  for (int i = 0; i < NUM_TASKS && i < ROWS_PER_PAGE; i++) drawRow(i);
  drawNav(0, 5);
}

// ---------- Touch ----------
// Returns true and fills x,y (screen pixels) if the screen is being touched
bool readTouch(int& x, int& y) {
  if (!ts.touched()) return false;
  TS_Point p = ts.getPoint();
  if (p.z < 200) return false;
  long rx = TOUCH_SWAP_XY ? p.y : p.x;
  long ry = TOUCH_SWAP_XY ? p.x : p.y;
  x = constrain(map(rx, TOUCH_X_MIN, TOUCH_X_MAX, 0, SCREEN_W - 1), 0, SCREEN_W - 1);
  y = constrain(map(ry, TOUCH_Y_MIN, TOUCH_Y_MAX, 0, SCREEN_H - 1), 0, SCREEN_H - 1);
  return true;
}

// Which task row (if any) contains screen point (x, y)
int rowAt(int x, int y) {
  if (x < ROW_X || x >= ROW_X + ROW_W) return -1;
  for (int i = 0; i < NUM_TASKS && i < ROWS_PER_PAGE; i++) {
    int top = ROW_Y0 + i * (ROW_H + ROW_GAP);
    if (y >= top && y < top + ROW_H) return i;
  }
  return -1;
}

// ---------- Arduino ----------
void setup() {
  Serial.begin(115200);
  tft.init();
  tft.setRotation(0);   // portrait, USB at the bottom

  touchSpi.begin(XPT_CLK, XPT_MISO, XPT_MOSI, XPT_CS);
  ts.begin(touchSpi);
  ts.setRotation(0);

  row.setColorDepth(16);
  if (!row.createSprite(ROW_W, ROW_H)) {
    Serial.println("Row sprite allocation failed!");
  }

  drawScreen();
  Serial.println("Stella's Day drawn.");
}

bool wasTouched = false;

void loop() {
  int x, y;
  bool touching = readTouch(x, y);

  // Act on the moment the finger first lands, then ignore until it lifts
  if (touching && !wasTouched) {
    int i = rowAt(x, y);
    Serial.printf("tap (%d,%d) -> row %d\n", x, y, i);
    if (i >= 0) {
      tasks[i].done = !tasks[i].done;
      drawRow(i);
    }
  }
  wasTouched = touching;
  delay(10);
}
