"""Slice icons out of the ChatGPT mockup and emit them as RGB565 C arrays
for TFT_eSPI's pushImage(), using 0xF81F (magenta) as the transparent key.

Run with a Python that has Pillow installed:
    python3 make_icons.py
"""
from PIL import Image
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'main_screen_mockup.png')
OUT_H = os.path.join(HERE, '..', 'stella_todo', 'icons.h')
PREVIEW_DIR = os.path.join(HERE, 'icons')

SIZE = 32          # native icon box, pixels
KEY = 0xF81F       # transparent colour key (pure magenta in RGB565)
BG_TOL = 28        # how close to the card colour counts as "background"

# name: crop box in mockup pixel coords (left, top, right, bottom)
ICONS = {
    'heart':      (60,  65, 180, 175),
    'flower':     (700, 172, 820, 280),
    'toothbrush': (80, 335, 250, 475),
    'shirt':      (80, 520, 235, 665),
    'cereal':     (70, 720, 245, 865),
    'soccer':     (60, 905, 240, 1065),
    'books':      (75, 1105, 235, 1245),
}

def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

def near(c1, c2, tol):
    return all(abs(a - b) <= tol for a, b in zip(c1, c2))

src = Image.open(SRC).convert('RGB')
out = ['// Auto-generated by design/make_icons.py from design/main_screen_mockup.png',
       '// RGB565 icons, %dx%d, transparent key 0x%04X' % (SIZE, SIZE, KEY),
       '#pragma once', '#include <stdint.h>', '',
       '#define ICON_SIZE %d' % SIZE,
       '#define ICON_KEY 0x%04X' % KEY, '']

for name, box in ICONS.items():
    crop = src.crop(box)
    w, h = crop.size
    # Background colour = median-ish of the four corners
    corners = [crop.getpixel(p) for p in [(1,1),(w-2,1),(1,h-2),(w-2,h-2)]]
    bg = tuple(sorted(c[i] for c in corners)[1] for i in range(3))

    # Build RGBA: alpha 0 where pixel is close to the card background
    rgba = Image.new('RGBA', crop.size)
    px = crop.load(); dst = rgba.load()
    for y in range(h):
        for x in range(w):
            c = px[x, y]
            dst[x, y] = (*c, 0) if near(c, bg, BG_TOL) else (*c, 255)

    # Fit into SIZE x SIZE box preserving aspect, centred
    rgba.thumbnail((SIZE, SIZE), Image.LANCZOS)
    canvas = Image.new('RGBA', (SIZE, SIZE), (0, 0, 0, 0))
    canvas.paste(rgba, ((SIZE - rgba.width) // 2, (SIZE - rgba.height) // 2))

    # Un-blend the card colour out of semi-transparent edge pixels
    final = Image.new('RGB', (SIZE, SIZE), (255, 0, 255))
    fp = final.load(); cp = canvas.load()
    vals = []
    for y in range(SIZE):
        for x in range(SIZE):
            r, g, b, a = cp[x, y]
            if a < 96:
                vals.append(KEY); continue
            if a < 255:
                f = a / 255.0
                r = max(0, min(255, int((r - (1 - f) * bg[0]) / f)))
                g = max(0, min(255, int((g - (1 - f) * bg[1]) / f)))
                b = max(0, min(255, int((b - (1 - f) * bg[2]) / f)))
            v = rgb565(r, g, b)
            if v == KEY: v = 0xF81E   # avoid accidental key collisions
            fp[x, y] = (r, g, b)
            vals.append(v)
    final.save(os.path.join(PREVIEW_DIR, name + '.png'))

    out.append('const uint16_t icon_%s[%d] PROGMEM = {' % (name, SIZE * SIZE))
    for i in range(0, len(vals), 16):
        out.append('  ' + ', '.join('0x%04X' % v for v in vals[i:i+16]) + ',')
    out.append('};'); out.append('')
    print(f'{name:11s} bg=#{bg[0]:02X}{bg[1]:02X}{bg[2]:02X}')

with open(OUT_H, 'w') as f:
    f.write('\n'.join(out))
print('wrote', os.path.abspath(OUT_H))
