"""Render a set of emoji from the macOS Apple Color Emoji font into 32x32
RGB565 C arrays for TFT_eSPI (transparent key 0xF81F), appended to
stella_todo/icons.h after the mockup-sliced icons.

Also writes design/icons/<name>.png previews and prints the JS/C++ tables
to paste into the portal and firmware.

Run with a Python that has Pillow:  python3 make_emoji_icons.py
"""
from PIL import Image, ImageFont, ImageDraw
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, '..', 'stella_todo', 'icons.h')
PREVIEW_DIR = os.path.join(HERE, 'icons')
FONT = "/System/Library/Fonts/Apple Color Emoji.ttc"
SIZE, KEY, RENDER = 32, 0xF81F, 160

# name: emoji.  Keep names stable - they're stored in the portal's data.
EMOJI = {
    # routine
    'hairbrush': '🪮', 'backpack': '🎒', 'vitamin': '💊', 'pencil': '✏️',
    'homework': '📝', 'shower': '🚿', 'bath': '🛁', 'bed': '🛏️',
    'moon': '🌙', 'sun': '☀️', 'clock': '⏰', 'socks': '🧦', 'shoes': '👟',
    'coat': '🧥', 'pajamas': '👚', 'laundry': '🧺', 'trash': '🗑️',
    'dishes': '🍽️', 'toys': '🧸', 'plant': '🪴', 'water': '💧',
    'milk': '🥛', 'apple': '🍎', 'lunch': '🥪', 'banana': '🍌',
    # pets & animals
    'dog': '🐶', 'cat': '🐱', 'fish': '🐟',
    # activities
    'ballet': '🩰', 'swim': '🏊', 'bike': '🚲', 'piano': '🎹', 'music': '🎵',
    'basketball': '🏀', 'tennis': '🎾', 'gymnastics': '🤸', 'dance': '💃',
    'art': '🎨', 'game': '🎮', 'tv': '📺', 'tablet': '📱',
    # places & events
    'school': '🏫', 'bus': '🚌', 'car': '🚗', 'doctor': '🩺', 'dentist': '🦷',
    'gift': '🎁', 'cake': '🎂', 'party': '🎉', 'umbrella': '☂️',
    # fun
    'star': '⭐', 'sparkles': '✨', 'rainbow': '🌈', 'unicorn': '🦄',
    'medal': '🏅', 'smile': '😊',
}

def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

font = ImageFont.truetype(FONT, RENDER)
out = ['', '// ---- Emoji icons (Apple Color Emoji), generated by design/make_emoji_icons.py ----', '']
names = []
for name, emoji in EMOJI.items():
    big = Image.new('RGBA', (RENDER * 2, RENDER * 2), (0, 0, 0, 0))
    ImageDraw.Draw(big).text((RENDER // 2, RENDER // 2), emoji, font=font, embedded_color=True)
    bbox = big.getbbox()
    if not bbox:
        print('MISSING glyph for', name, emoji); continue
    glyph = big.crop(bbox)
    glyph.thumbnail((SIZE, SIZE), Image.LANCZOS)
    canvas = Image.new('RGBA', (SIZE, SIZE), (0, 0, 0, 0))
    canvas.paste(glyph, ((SIZE - glyph.width) // 2, (SIZE - glyph.height) // 2))

    # Flatten: semi-transparent edge pixels get blended toward a neutral light
    # card colour so they don't fringe dark on the pastel backgrounds.
    bg = (0xEE, 0xEE, 0xF8)
    preview = Image.new('RGB', (SIZE, SIZE), (255, 0, 255))
    vals = []
    px = canvas.load(); pp = preview.load()
    for y in range(SIZE):
        for x in range(SIZE):
            r, g, b, a = px[x, y]
            if a < 80:
                vals.append(KEY); continue
            f = a / 255.0
            r = int(r * f + bg[0] * (1 - f)); g = int(g * f + bg[1] * (1 - f)); b = int(b * f + bg[2] * (1 - f))
            v = rgb565(r, g, b)
            if v == KEY: v = 0xF81E
            pp[x, y] = (r, g, b)
            vals.append(v)
    preview.save(os.path.join(PREVIEW_DIR, name + '.png'))
    names.append(name)
    out.append('const uint16_t icon_%s[%d] PROGMEM = {' % (name, SIZE * SIZE))
    for i in range(0, len(vals), 16):
        out.append('  ' + ', '.join('0x%04X' % v for v in vals[i:i + 16]) + ',')
    out.append('};'); out.append('')

# Name -> data lookup table covering the mockup icons and the emoji ones
MOCKUP = ['heart', 'flower', 'toothbrush', 'shirt', 'cereal', 'soccer', 'books']
out.append('struct IconEntry { const char* name; const uint16_t* data; };')
out.append('const IconEntry ICON_TABLE[] = {')
for n in MOCKUP + names:
    out.append('  { "%s", icon_%s },' % (n, n))
out.append('};')
out.append('const int ICON_COUNT = sizeof(ICON_TABLE) / sizeof(ICON_TABLE[0]);')
out.append('')

# Append to icons.h (replace any previous emoji block)
src = open(OUT_H).read()
marker = out[1]
if marker in src:
    src = src[:src.index(marker)].rstrip('\n') + '\n'
open(OUT_H, 'w').write(src + '\n'.join(out))

print('added %d icons to icons.h' % len(names))
print('\n// portal ICONS entries:')
print(', '.join('%s: "%s"' % (n, EMOJI[n]) for n in names))
